### PR TITLE
Noticeable upgrade

### PR DESCRIPTION
**Pull request by Bekos-von-Nimmerland**
It is significant code change related to gameplay. There I added crawl-on-button support , nicer and separate animation for crawling , deleted old hitbox code and introduced new ones(now, when sneaking, hitbox height decreases to 1.5 block and may not decrease if SNEAKING_TOGGLE is false; when swimming or crawling, hibox decreases to 0.6 height and player may not be shot easily while crawling behind 1 block wall or swimming. Though, there still are troubles with speed(player like soldier crawls faster when not under block, looks funny) and networking. Networking issue is that when one player at server presses crawl button, others get hitbox and animation of crawling at button pressor's client , but other player's gameplay is not affected, thus it is only cosmetic issue and looks very funny(imagine crawling player jumping parkour or digging 1x2 tunnel). However, when one player has real reason to crawl - e.g. block over him/her, his hitbox and animation are shown correctly. Anyways, thanks to Kaydax and bagu_chan for such a great job.
P.S. server I used to test my fork was private, so none of the code left in fourth-party hands.
P.S.S. Won't be so disappointed if my fork will be rejected, just will use it for private gameplay.

### CODE REVIEW

**Comment by Kaydax** [comment]
I will check this out, thanks for the PR! The changes seem good apart from the crawl button, as that kinda removes the purpose of the mod being a faithful backport of crawling and swimming in 1.13+

**Comment by Kaydax** [comment]
Ok so the crawl button feature is really broken. Crawling in the open makes you crawl at walking speed, that is not normal. Also if you use the crawl button while swimming it breaks the swimming animation, same with going into a one block tall space while swimming, since the animations then conflict with each other. Other then that, the new collision code may be useful.

**Review by Kaydax — CHANGES_REQUESTED** [review]
Remove crawling button, remove separate crawling animation as it both conflicts with the swimming animation and is not faithful to 1.13+ style.

**Comment by Bekos-von-Nimmerland** [comment]
Okay, sir! Thanks for feedback, I will remove the button and, in case of animation issue continues after button removal, new animation will be removed too. (Vanilla 1.13 crawling animation looks really weird, Mojang and Microsoft programmers stopped preying upon mices)(=slacked off))). Will do next days, because it's night outside my house IRL and my brain is a bit overloaded. Have a nice day

**Comment by Bekos-von-Nimmerland** [comment]
That's done, button exterminated, new animation kept as it no longer breaks swimming.

**Comment by Bekos-von-Nimmerland** [comment]
Still in trouble deleting "init" folder from github, just do not include it or delete yourself if possible.
Mit Respekt!

**Comment by Kaydax** [comment]
I mean i still on the fence about the animation, It adds more code that clutters things up as well as just doesn't fit the true nature of the mod. I may abstract it and make it configurable though

**Comment by Bekos-von-Nimmerland** [comment]
Of course, it would be really great if you may. anyway its depends on your decision. You may close the pull request, I won't be disappointed. Just tried to contribute. Have a nice day, sir

**Pull request closed without merging**
